name: "Build and Deploy"
on:
  push:
    branches:
      - deploy
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: jeffreytse/jekyll-deploy-action@v0.5.0
        with:
          provider: 'github'
          token: ${{ secrets.BLOG_PUSH_TOKEN}}
          repository: 'pilyang/pilyang.github.io'
          branch: "gh-pages"
          jekyll_src: './'
          jekyll_cfg: '_config.yml'
          jekyll_baseurl: ''
          bundler_ver: '>=0'
          cname: ''
          actor: ''

