name: "Build and Deploy"
on:
  push:
    branches:
      - deploy
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
jobs:
  build_and_deply:
    runs-on: ubuntu-lates
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: jeffreytse/jekyll-deploy-action@v0.5.0
        with:
          provider: 'github'
          token: ${{ secrets.BLOG_PUSH_TOKEN}}
          repository: 'pilyang/pilyang.github.io'
          branch: "hg-pages"
          jekyll_src: './'
          jekyll_cfg: '_config.yml'
          bundler_ver: '>=0'
          jekyll_baseurl: ''
          cname: 'blog.pilyang.com'
          actor: ''

